version: "3.8"

services:
  api:
    build:
      context: ./_api
      dockerfile: Dockerfile
    ports:
      - "7199:7199"
    networks:
      - app-network
    
  client: # Renamed from 'frontend' to 'client' for consistency
    build:
      context: ./_client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # This enables polling for file changes
      - REACT_APP_API_BASE_URL=http://api:7199/api
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./_client/src:/app/src
      - ./_client/public:/app/public
      - /app/node_modules

networks:
  app-network:
    driver: bridge

