version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile # This should be the path to your API's Dockerfile
    ports:
      - "7199:7199"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile # This should be the path to your frontend's Dockerfile
    volumes:
      -  # Mounts the project directory to a directory in the container
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # This enables polling for file changes
      - REACT_APP_API_BASE_URL=http://api:7199/api # Adjusted to use the service name for internal communication
      - REACT_APP_IMAGE_PATH=/images
    depends_on:
      - api
    networks:
      - app-network
    command: ["npm", "start"] # Overrides the CMD defined in your Dockerfile if necessary

networks:
  app-network:
    driver: bridge
