version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./_api/Dockerfile
    ports:
      - "7199:8080"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment

  client: # Renamed from 'frontend' to 'client' for consistency
    build:
      context: .
      dockerfile: ./_client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      #- CHOKIDAR_USEPOLLING=true # This enables polling for file changes
      - REACT_APP_API_BASE_URL=http://api:8080/api
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./_client/src:/app/src
      - ./_client/dist:/app/dist
      - ./_client/public:/app/public
      - /app/node_modules

networks:
  app-network:
    driver: bridge
